### ISSUE TITLE
AttributeError: 'AioHttpTransport' object has no attribute '_url'

### ISSUE THREAD

**Issue by kvspb** [getsentry/raven-aiohttp#13]
raven-6.0.0
raven_aiohttp-0.4.0

raven_aiohttp.py", line 110, in async_send
return self._async_send(self._url, *args, **kwargs)
AttributeError: 'AioHttpTransport' object has no attribute '_url'

**Comment by mitsuhiko** [comment]
This should be fixed in aiohttp 0.5.
