### ISSUE TITLE
0.6.0 PyPi release

### ISSUE THREAD

**Issue by hellysmile** [getsentry/raven-aiohttp#20]
Here is minor fix regarding supported Python versions for aiohttp

https://github.com/getsentry/raven-aiohttp/pull/19

Can we push new PyPi release after this minor fix?

**Comment by hellysmile** [comment]
@ashwoods @mitsuhiko sorry for direct ping, but have no idea who else can push PyPi.

**Comment by ashwoods** [comment]
@hellysmile will do on monday.

**Comment by Kentzo** [comment]
Looking forward to it :)

**Comment by Kentzo** [comment]
Perhaps [Travis's ability](https://docs.travis-ci.com/user/deployment/pypi/) to publish on PyPI should be integrated with the repo?

**Comment by Kentzo** [comment]
Is anything else holding the release?

**Comment by webknjaz** [comment]
@Kentzo if you look at the config, you'll see it's already integrated :)

@ashwoods only needs to push new `0.6.0` tag to trigger the process.

**Comment by Kentzo** [comment]
There is a tag, but still no release on PyPI

**Comment by webknjaz** [comment]
Oh, they broke integration with branch filtering:  https://github.com/getsentry/raven-aiohttp/commit/44201c69728feeb78d30061d4bd697919d51ee5d

**Comment by webknjaz** [comment]
@ashwoods would you accept a PR fixing Travis config?

**Comment by ashwoods** [comment]
@webknjaz no need. switching our build/deploy pipelines to probot-deploy.

**Comment by webknjaz** [comment]
@ashwoods sounds interesting, is there any link to this `probot-deploy` you refer to? is it open-source?

**Comment by webknjaz** [comment]
@ashwoods sounds interesting, is there any link to this `probot-deploy` you refer to? is it open-source?
