### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ca_certs'

### ISSUE THREAD

**Issue by orf** [getsentry/raven-aiohttp#3]
AioHttpTransport doesn't seem to accept a `ca_certs` keyword argument, which causes the error in the title. Since `HTTPTransport` accepts this keyword argument then shouldn't AioHttpTransport?

**Comment by asvetlov** [comment]
From my understanding optional parameters are not mandatory but it's good to support them all.

**Comment by ashwoods** [comment]
closing this as stale.
