### ISSUE TITLE
asyncio.async deprecated alias to ensure_future()

### ISSUE THREAD

**Issue by AlJohri** [getsentry/raven-aiohttp#8]
https://docs.python.org/3/library/asyncio-task.html#asyncio.async
https://docs.python.org/3/library/asyncio-task.html#asyncio.ensure_future

**Comment by asvetlov** [comment]
@AlJohri #20 addresses the issue

**Comment by asvetlov** [comment]
I think the issue can be closed.
Fixed by #6
